-- 
-- Inherit table from CLAROPAY database with promotions data.
-- 
-- Date:     Nov 14th, 2019.
-- Database: CLAROPAY
-- 
CREATE TABLE `CAT_PROMOTION` (
  `PROMOTION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION`  VARCHAR(500) NOT NULL,
  `LOGO_PATH`    VARCHAR(100) NOT NULL,
  `VALIDITY`     VARCHAR(100) NOT NULL,
  `STORE_ID`     INT(11) NOT NULL,
  `STATUS`       VARCHAR(20) NOT NULL,
  `PRIORITY`     INT(11) NOT NULL,
  PRIMARY KEY (`PROMOTION_ID`),
  KEY `CAT_PROMOTION_FK` (`STORE_ID`),
  CONSTRAINT `CAT_PROMOTION_FK`
    FOREIGN KEY (`STORE_ID`)
    REFERENCES `CAT_STORE` (`STORE_ID`)
    ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;